source:
  type: db
  uri: postgres://postgres:pass@localhost:5432/postgres
  table: mydata
output:
  type: csv
  path: out.csv
  separator: ","
rules:
  - column: name
    method: hash
    algorithm: md5
    salt: qsdjkazdhjkb
  - column: name
    method: fake
    faker_type: firstname
  - column: cc
    method: mask_right
    n_chars: 3
    mask_char: "x"
  - column: birthdate
    method: mask_left
    n_chars: 4
    mask_char: x