name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"

jobs:
  ci:
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Lint code with ruff
        run: poetry run poe lint

      - name: Check types with mypy
        run: poetry run poe type

      - name: Test with pytest
        run: poetry run poe test

      - name: Code coverage
        run: |
          COV_OUTPUT=$(poetry run poe cov --format=markdown)
          echo $COV_OUTPUT
          echo '## Test Coverage Report\n' >> $GITHUB_STEP_SUMMARY
          # Remove the first line of the coverage report
          echo "$COV_OUTPUT" | tail -n +2 >> $GITHUB_STEP_SUMMARY
